# Generated by Django 5.1.7 on 2025-04-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_address_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='order_address',
        ),
    ]
